## fechas

para representar fecah y hora se utiliza datos especiales: __datatime64__ 


para representar intervalos s e usa __timedelta64__

usualmente leemos la fecha como string , para convertirlo en datatime se usa la funciona __pd.to_datatime__  que permite controlar el formato

In [1]:
import pandas as pd 
import numpy as np
import matplotlib

In [2]:
data = pd.read_csv("/home/balthazar/Escritorio/progra/Analisis-de-datos/teoria/modulo 5/csv/goldprice.csv")
data.dtypes

Date         str
Price    float64
Open     float64
High     float64
Low      float64
dtype: object

In [4]:
data["Date"] = pd.to_datetime(data["Date"])
data.dtypes

Date     datetime64[us]
Price           float64
Open            float64
High            float64
Low             float64
dtype: object

In [5]:
data["Date"].dt.year

0       2018
1       2018
2       2018
3       2018
4       2018
        ...
9766    1980
9767    1980
9768    1979
9769    1979
9770    1979
Name: Date, Length: 9771, dtype: int32

podemos encontrar la fecha mas antigua con min y la mas reciente con max

In [6]:
data["Date"].min(),data["Date"].max()

(Timestamp('1979-12-27 00:00:00'), Timestamp('2018-08-01 00:00:00'))

In [8]:
data["Date"].max()-data["Date"].min()

Timedelta('14097 days 00:00:00')

Cuando tenemos datos relacionados a fechas, podemos
utilizar la serie de tiempo como índice. Esto le da mucha
funcionalidad ya que podemos seleccionar datos
refiriéndonos a las fechas.



Para utilizar la columna de fechas como índice podemos
usar set_index. En este caso pandas crea un tipo de
dato especial, el DatetimeIndex. Como sólo se trata de
fechas podemos acceder a los métodos directamente,
sin pasar por el atributo dt.



Ahora podemos seleccionar los datos según criterios
temporales, como todos los datos de un año o de todos
los lunes, usando indexing y filtros.

In [ ]:
data.set_index("Date",inplace=True)
data

           Date   Price     Open    High      Low
0    2018-08-01  1216.6  1223.40  1223.4  1216.20
1    2018-07-31  1223.7  1220.40  1228.1  1213.00
2    2018-07-30  1221.3  1222.50  1223.9  1218.10
3    2018-07-27  1222.2  1223.50  1226.8  1216.70
4    2018-07-26  1225.3  1227.80  1227.8  1227.80
...         ...     ...      ...     ...      ...
9766 1980-01-03   625.0   627.00   640.0   603.00
9767 1980-01-02   575.5   562.50   577.0   558.00
9768 1979-12-31   533.6   527.88   534.5   527.88
9769 1979-12-28   517.8   516.00   517.8   510.40
9770 1979-12-27   515.5   517.00   517.0   513.00

[9771 rows x 5 columns]

In [29]:
data.loc["2010"]

             Price    Open    High     Low
Date
2010-12-31  1421.1  1405.7  1420.7  1405.7
2010-12-30  1405.6  1413.8  1413.8  1403.1
2010-12-29  1413.1  1403.4  1412.2  1402.9
2010-12-28  1405.2  1389.8  1406.7  1389.8
2010-12-27  1382.4  1373.5  1384.2  1373.5
...            ...     ...     ...     ...
2010-01-08  1138.2  1124.9  1136.9  1122.7
2010-01-07  1133.1  1132.1  1133.0  1129.2
2010-01-06  1135.9  1120.7  1139.2  1120.7
2010-01-05  1118.1  1122.0  1126.5  1115.0
2010-01-04  1117.7  1097.1  1122.3  1097.1

[252 rows x 4 columns]